"use client";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { useState } from "react";

export function TwoFactorSetup() {
    const [isEnabled, setIsEnabled] = useState(false);
    const [showSetup, setShowSetup] = useState(false);

    // Mock QR Data
    const qrCodeUrl = "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=otpauth://totp/Vesatio:user@example.com?secret=JBSWY3DPEHPK3PXP&issuer=Vesatio";

    return (
        <div className="space-y-6">
             <div className="flex items-center justify-between">
                <div>
                     <h3 className="text-lg font-medium text-white">Autenticação de Dois Fatores (2FA)</h3>
                    <p className="text-sm text-diamond-muted">Adicione uma camada extra de segurança à sua conta.</p>
                </div>
                <div className="flex items-center gap-3">
                    <span className="text-sm font-medium text-white">{isEnabled ? "Ativado" : "Desativado"}</span>
                     <Switch 
                        checked={isEnabled} 
                        onCheckedChange={(checked) => {
                            if (checked) setShowSetup(true);
                            else setIsEnabled(false);
                        }} 
                    />
                </div>
            </div>

            {showSetup && !isEnabled && (
                <div className="p-6 bg-onyx-100 rounded-lg border border-gold/20 space-y-6 animate-in fade-in slide-in-from-top-4">
                    <div className="flex flex-col md:flex-row gap-8 items-center">
                        <div className="bg-white p-2 rounded-lg">
                            {/* In real implementation, this would be generated by Supabase MFA */}
                            <img src={qrCodeUrl} alt="QR Code" className="w-32 h-32" />
                        </div>
                        <div className="space-y-4 flex-1">
                            <h4 className="font-serif text-lg text-gold">Configurar Authenticator</h4>
                            <ol className="list-decimal list-inside space-y-2 text-sm text-diamond-muted">
                                <li>Instale uma app de autenticação (Google Authenticator, Authy).</li>
                                <li>Digitalize o código QR.</li>
                                <li>Insira o código de 6 dígitos gerado pela app.</li>
                            </ol>
                            
                            <div className="flex gap-2 max-w-sm">
                                <Input placeholder="000 000" className="text-center tracking-widest text-lg" maxLength={6} />
                                <Button className="btn-primary" onClick={() => { setIsEnabled(true); setShowSetup(false); }}>
                                    Verificar
                                </Button>
                            </div>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}
